# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKWallReader' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VKWallReader
pod 'AFNetworking', '~> 3.0'

  target 'VKWallReaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
